import pytest
import unittest.mock
from floto.api import ActivityType
import floto.api

# This is a hack to overcome the initial lack of botocore.client.SWF which is autogenerated
class Client_Mock:
    def register_activity_type(self, **args):
        pass

class TestActivityTypeAPICall:

    def test_get_properties(self):
        a = ActivityType()
        p = a._get_properties()
        assert 'defaultTaskScheduleToCloseTimeout' in p

    def test_set_args(self):
        a = ActivityType(default_task_heartbeat_timeout='120', 
                default_task_schedule_to_start_timeout='180')
        p = a._get_properties()
        assert p['defaultTaskHeartbeatTimeout'] == '120'
        assert p['defaultTaskScheduleToStartTimeout'] == '180'


